### ISSUE TITLE
optimization.runtimeChunk produces wrong remoteEntry.js

### ISSUE THREAD

**Issue by ChrisSG** [module-federation/rollup-federation#4]
When enabling runtimeChunk the remote entry will produce code in the form of:

`var Foo;Foo=
(window["webpackJsonpFoo"] = window["webpackJsonpFoo"] || []).push([["Foo"],{`

Since push returns 1 the code wil not automatically execute for the variable Foo...

**Comment by maraisr** [comment]
Hello @ChrisSG 👋 that is a webpack error, and not something rollup related. Can you please re-raise this over at https://github.com/webpack/webpack.

But just an fyi, you cannot use runtimeChunk with module federation, because the runtime's are different. That being said we probably should warn the user about that. SO yeah can you please re-raise this over at the webpack repo. Thanks!

**Comment by ChrisSG** [comment]
It is actually when using the following:

```   
     optimization: {
            runtimeChunk: <<condition_for_host_container_here>> ? {
                name: entrypoint => `runtime~${entrypoint.name}`
            } : undefined
        },
``` 

This setup assumes one host and multiple remotes. Presumably won't work with bidirectional situations...

**Comment by maraisr** [comment]
Is your runtimeChunk set to `undefined` for the host? Because that needs to be.

For your consumers, if you're wanting to use runtimeChunk, you cannot expose anything.

I will reiterate this; please go re-raise this issue in the webpack repo. This repo is for rollup integration.
